project/blog/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Category(models.Model):
    class Meta():
        db_table = 'categoryy'
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Meme(models.Model):
    class Meta():
        db_table = 'Memasiki'
    image = models.ImageField(
        "Картинка мема", upload_to='images/')
    pub_date = models.DateTimeField("Дата публикации", auto_now_add=True)
    category = models.ForeignKey(Category)

project/blog/views.py
from django.http import HttpResponse
from django.shortcuts import get_list_or_404, render
from django.views import generic

from .models import Meme

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return Meme.objects.order_by('-pub_date')[:15]

project/project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet ">
  </head>

  <body>
    <div class="wrap ">
      {% include "project/header.html " %}{% block content %} {% endblock %} {% include "project/footer.html " %}
    </div>
  </body>

</html>

project/project/templates/blog/index.html
{% extends "base.html" %} {% block content %} {% for meme in meme_list %}
<li>
  <img src="{{meme.image.url }}" alt="">
</li>
{% endfor %} {% endblock content %}

project/project/templates/project/footer.html
<div>
  FOOTER
</div>

project/project/templates/project/header.html
<div>
  HEADER
</div>